### ISSUE TITLE
Android Example Not Working

### ISSUE THREAD

**Issue by kprathap23** [MailCore/mailcore2#1055]
Hi,

1) I have followed the instructions to build the AndroidExample App. Build successful. I tried to do run Android Example with .aar file in libs folder. I have changed MessageSyncManger with username,password,host and port number.

        session.setUsername("kprathap23@gmail.com");
        session.setPassword("mypassword");
        session.setHostname("imap.gmail.com");
        session.setPort(993);
        session.setConnectionType(ConnectionType.ConnectionTypeTLS);

I am getting following error and app crashes.
/com.libmailcore.androidexample A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x766e6f6f in tid 13683 (.androidexample)

How can i fix this issue.

2) The minimum sdk for the AndroidExample App and .aar Libary Project is set to 21. 

if i change the minimum sdk in the app/build.grade file to 14 then

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library C:\Users\pratap\Desktop\mailcore2-master\example\android\AndroidExample\app\build\intermediates\exploded-aar\mailcore2-android-1\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.libmailcore.library" to force usage

is MailCore2 does not support lower than Lollypop devices ? 

3) I Found LoginActivity in the AndroidManifest.xml file but i did not found Activity java file.

Thanks,
Pratap.

**Comment by kprathap23** [comment]
Some one suggested in stackoverflow to use android:hardwareAccelerated=flase, I have tried to use  android:hardwareAccelerated="false" and android:allowClearUserData="true" for application tag in manifest. But it is not working either.

I found that it is related to Memory related error in the ndk after searching in google for Fatal signal 11 Error.

**Comment by dinhviethoa** [comment]
I haven't tried to rebuild MailCore on version lower than lollipop yet. We could try.
Also, for the crash, I would need to reproduce it.
Does it crash when you use a wrong password or does it always crash?

**Comment by kprathap23** [comment]
Thanks for your reply.It is always crashing with correct username and password.

I have not checked with wrong password.

**Comment by dinhviethoa** [comment]
Could you get the call stack of the crash?

**Comment by kprathap23** [comment]
Always showing this error, after crash 
/com.libmailcore.androidexample A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x766e6f6f in tid 13683 (.androidexample)

**Comment by appapurapu** [comment]
Hi Dinhviethoa,

I am not able successful to build Android Example for android and below are the logs.
Could you please update me what I am missing..?

##############
rappapurapu@MAVBGL-656 /D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android (                                                        
master)                                                                                                                                                         
$ export ANDROID_SDK="C:\Program Files (x86)\Android\sdk"                                                                                                       
                                                                                                                                                                
rappapurapu@MAVBGL-656 /D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android (master)                                                 
$ export ANDROID_NDK="C:\Users\rappapurapu\Desktop\mingleClient\adt-bundle-windows-x86_64-20140702\NDK\android-ndk-r10"                                         
                                                                                                                                                                
rappapurapu@MAVBGL-656 /D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android (master)                                                 
$ ./build.sh                                                                                                                                                    
-- Building for: Visual Studio 12 2013                                                                                                                          
CMake Error at CMakeLists.txt:60 (message):                                                                                                                     
  ERROR: Could not find icu4c                                                                                                                                   
                                                                                                                                                                
                                                                                                                                                                
-- Configuring incomplete, errors occurred!                                                                                                                     
See also "D:/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android/cmake-build/CMakeFiles/CMakeOutput.log".                              
cp: cannot stat `/D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android/cmake-build/src/include/MailCore': No such file or directory   
C:\Users\rappapurapu\Desktop\mingleClient\adt-bundle-windows-x86_64-20140702\NDK\android-ndk-r10/ndk-build: line 324: /c/Program: No such file or directory     
cp: cannot stat `/D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android/libs/armeabi/libMailCore.so': No such file or directory        
C:\Users\rappapurapu\Desktop\mingleClient\adt-bundle-windows-x86_64-20140702\NDK\android-ndk-r10/ndk-build: line 324: /c/Program: No such file or directory     
cp: cannot stat `/D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android/libs/armeabi-v7a/libMailCore.so': No such file or directory    
C:\Users\rappapurapu\Desktop\mingleClient\adt-bundle-windows-x86_64-20140702\NDK\android-ndk-r10/ndk-build: line 324: /c/Program: No such file or directory     
cp: cannot stat `/D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android/libs/x86/libMailCore.so': No such file or directory            
C:\Users\rappapurapu\Desktop\mingleClient\adt-bundle-windows-x86_64-20140702\NDK\android-ndk-r10/ndk-build: line 324: /c/Program: No such file or directory     
cp: cannot stat `/D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android/libs/x86_64/libMailCore.so': No such file or directory         
javac: invalid flag: (x86)\Android\sdk/platforms/android-21/android.jar                                                                                         
Usage: javac <options> <source files>                                                                                                                           
use -help for a list of possible options                                                                                                                        
                                                                                                                                                                
zip error: Invalid command arguments (short option 'y' not supported)                                                                                           
rm: cannot remove directory `/D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android/bin': Permission denied                            
                                                                                                                                                                
rappapurapu@MAVBGL-656 /D/ClientDevelopment/phone2_0/VoiceMailClient/mailCore2/mailcore2/build-android (master)                                                 
$                                                                                                                                                              
##############

**Comment by kprathap23** [comment]
1) I have tested with wrong password also. app crashing
/com.libmailcore.androidexample A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x766e6f6f in tid 13683 (.androidexample).

2) I have tried build the mailcore2 with android-ndk-9 , it is downloaded some third party libs and after some time the console shows permission denied.

Which Version Android ndk  do we need to use to build the Libary android-ndk-9 or 10.

**Comment by appapurapu** [comment]
Hi Kprathap23,

Did you successful to build the android example for android or using the package: mailcore2-android-1.aar?

Hi dinhviethoa

Below is the crash log where SIGSEGV signal 11 is coming after using the mailcore2-android-1.aar file..

###########
02-09 11:20:04.698: W/AudioTrack(356): AUDIO_OUTPUT_FLAG_FAST denied by client
02-09 11:20:04.827: I/ActivityManager(356): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.libmailcore.androidexample/.MessageViewListActivity (has extras)} from uid 10007 on display 0
02-09 11:20:04.966: I/Choreographer(647): Skipped 45 frames!  The application may be doing too much work on its main thread.
02-09 11:20:05.343: I/ActivityManager(356): Start proc com.libmailcore.androidexample for activity com.libmailcore.androidexample/.MessageViewListActivity: pid=954 uid=10053 gids={50053, 9997, 3003} abi=armeabi-v7a
02-09 11:20:05.430: I/Choreographer(356): Skipped 39 frames!  The application may be doing too much work on its main thread.
02-09 11:20:05.465: I/art(954): Not late-enabling -Xcheck:jni (already on)
02-09 11:20:05.963: I/ARMAssembler(53): generated scanline__00000077:03515104_00009001_00000000 [131 ipp] (153 ins) at [0xb5d511f0:0xb5d51454] in 10000000 ns
02-09 11:20:06.032: I/Choreographer(356): Skipped 33 frames!  The application may be doing too much work on its main thread.
02-09 11:20:06.171: I/ARMAssembler(53): generated scanline__00000077:03010104_00008001_00000000 [ 89 ipp] (110 ins) at [0xb5d51460:0xb5d51618] in 10000000 ns
02-09 11:20:06.668: I/art(954): Background sticky concurrent mark sweep GC freed 1474(71KB) AllocSpace objects, 0(0B) LOS objects, 17% free, 514KB/623KB, paused 1.235ms total 237.979ms
02-09 11:20:06.668: I/art(954): --------- beginning of crash
02-09 11:20:06.993: A/libc(954): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x766e6f6f in tid 954 (.androidexample)
02-09 11:20:07.041: I/DEBUG(61): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-09 11:20:07.042: I/DEBUG(61): Build fingerprint: 'generic/sdk_phone_armv7/generic:5.0/LRX09D/1504858:eng/test-keys'
02-09 11:20:07.042: I/DEBUG(61): Revision: '0'
02-09 11:20:07.042: I/DEBUG(61): ABI: 'arm'
02-09 11:20:07.043: I/DEBUG(61): pid: 954, tid: 954, name: .androidexample  >>> com.libmailcore.androidexample <<<
02-09 11:20:07.044: I/DEBUG(61): signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x766e6f6f
02-09 11:20:07.080: I/DEBUG(61):     r0 a70eb7b0  r1 00000000  r2 00000001  r3 766e6f63
02-09 11:20:07.084: I/DEBUG(61):     r4 000003e8  r5 beab4930  r6 b4ffefe8  r7 beab4960
02-09 11:20:07.087: I/DEBUG(61):     r8 beab4978  r9 b5007800  sl 00000000  fp beab4940
02-09 11:20:07.092: I/DEBUG(61):     ip b4fc14c0  sp beab4900  lr a79fe43d  pc a6e33942  cpsr 60000030
02-09 11:20:07.097: I/DEBUG(61): backtrace:
02-09 11:20:07.101: I/DEBUG(61):     #00 pc 00164942  /data/app/com.libmailcore.androidexample-2/lib/arm/libMailCore.so (Java_com_libmailcore_NativeObject_initWithNative+17)
02-09 11:20:07.106: I/DEBUG(61):     #01 pc 007fdc10  [stack]
02-09 11:20:07.889: I/DEBUG(61): Tombstone written to: /data/tombstones/tombstone_02
02-09 11:20:07.988: W/ActivityManager(356):   Force finishing activity com.libmailcore.androidexample/.MessageViewListActivity
02-09 11:20:08.027: I/Zygote(67): Process 954 exited due to signal (11)
02-09 11:20:08.314: I/WindowManager(356): Screenshot max retries 4 of Token{1972458c ActivityRecord{16909abf u0 com.libmailcore.androidexample/.MessageViewListActivity t14 f}} appWin=Window{213a1189 u0 Starting com.libmailcore.androidexample} drawState=4
02-09 11:20:08.316: E/ActivityManager(356): Invalid thumbnail dimensions: 288x288
02-09 11:20:08.336: W/ActivityManager(356): Exception thrown during pause
02-09 11:20:08.336: W/ActivityManager(356): android.os.DeadObjectException
02-09 11:20:08.336: W/ActivityManager(356): 	at android.os.BinderProxy.transactNative(Native Method)
02-09 11:20:08.336: W/ActivityManager(356): 	at android.os.BinderProxy.transact(Binder.java:479)
02-09 11:20:08.336: W/ActivityManager(356): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:701)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:852)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2754)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2611)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2448)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11507)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11404)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12083)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11599)
02-09 11:20:08.336: W/ActivityManager(356): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
02-09 11:20:08.375: E/lowmemorykiller(50): Error opening /proc/954/oom_score_adj; errno=2
02-09 11:20:08.468: I/ActivityManager(356): Process com.libmailcore.androidexample (pid 954) has died
02-09 11:20:08.819: I/Choreographer(647): Skipped 99 frames!  The application may be doing too much work on its main thread.
02-09 11:20:09.014: I/Choreographer(356): Skipped 55 frames!  The application may be doing too much work on its main thread.
02-09 11:20:09.724: I/Choreographer(356): Skipped 33 frames!  The application may be doing too much work on its main thread.
02-09 11:20:10.036: I/Choreographer(356): Skipped 70 frames!  The application may be doing too much work on its main thread.
02-09 11:20:11.552: W/AudioTrack(356): AUDIO_OUTPUT_FLAG_FAST denied by client
02-09 11:20:11.702: I/Choreographer(356): Skipped 41 frames!  The application may be doing too much work on its main thread.
02-09 11:20:11.811: W/InputMethodManagerService(356): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@24b5af0 attribute=null, token = android.os.BinderProxy@32b6019c
02-09 11:20:11.852: I/Choreographer(356): Skipped 32 frames!  The application may be doing too much work on its main thread.
02-09 11:20:12.106: D/TaskPersister(356): removeObsoleteFile: deleting file=14_task.xml
02-09 11:20:12.221: I/art(356): Background sticky concurrent mark sweep GC freed 12743(1009KB) AllocSpace objects, 1(16KB) LOS objects, 13% free, 6MB/8MB, paused 37.517ms total 398.614ms

###########

**Comment by denglevi** [comment]
i met the same problem as  kprathap23,when i use the mailcore2-android-1.aar to compile the app ,it  can run on Lollypop devices,but can not run on lower than 21 devices,so is there somebody know how to fix this issue.ths

**Comment by kprathap23** [comment]
Hi denglevi,

did you run the app successfully to get mails on Lollypop devices ?

**Comment by kprathap23** [comment]
Hi appapurapu,

No Sucees so far.I have build the project with .aar file in libs folder. Build Succeed
apk file generated, but application crashing .

**Comment by denglevi** [comment]
Hi kprathap23,i can run the app successfully on Lollypop devices

**Comment by kprathap23** [comment]
@denglevi ,
In which device you are testing. Can you share .apk file for me to test.

**Comment by denglevi** [comment]
@kprathap23 ,on my nexus virtual device,but cannot run on my htc which the system version is 4.4

**Comment by denglevi** [comment]
@kprathap23  nexus 5 can run successfully

**Comment by appapurapu** [comment]
Hi,

I have tried with Nexus 5 with X86 or x86_64 hardware acceleration ==> working to connect to gmail and fetch and displaying the messages.

But it is not working with Nexus 5 with other hardware acceleration. 
Also if you connect to your gmail account which has huge messages say 2000 or more, it is crashing to fetch all messages to display to user. This needs a fix.

Thanks,
RajaA

**Comment by dinhviethoa** [comment]
Does the crash happen only when running on the device or does it also happen in the emulator?

**Comment by appapurapu** [comment]
Hi Dinhviethoa,

I have tried on emulator only and not on target. I required to check on target and update you.

One more question, is only syncing & displaying messages from mStore works or any other functionality we can test for?

RajaA

**Comment by appapurapu** [comment]
Hi Dinhviethoa,

Using mailCore2, now I am able to build for android to geneate the *.aar file and I am able to connect to gmail and fetch messages.
Can we decode the wireshark traffic using this mailcore2? Basically to decode, we require
CLIENT RAND & MASTER SECRET.
CLIENT RAND can be read from client hello packet, but where to get the master secret? 
Are there any debug logs need to enable to get this?

Thanks,
RajaA

**Comment by dinhviethoa** [comment]
connectionLogger on IMAPSession should help.

**Comment by dinhviethoa** [comment]
Could you ask questions on stackoverflow instead?
Set the mailcore2 tag properly.

**Comment by appapurapu** [comment]
Thanks Dinhviethoa for your update!

**Comment by kprathap23** [comment]
@dinhviethoa 

Can you new update and release new *.aar file for lower than lollypop devices.

**Comment by appapurapu** [comment]
Hi

I built the aar file for android version 19 to 21. Please check whether it is useful to you?

Thanks,
RajaA

**Comment by kprathap23** [comment]
@appapurapu 

Can u share the .aar file.

**Comment by appapurapu** [comment]
Hi,

I am sorry, I am not able to attach this 17MB file here. I uploaded to dropbox.
Could you please download it from the below link:
https://www.dropbox.com/s/rm8k9fmtyfw8t0y/mailcore2-android-1.aar?dl=0

Thanks,
RajaA

**Comment by kprathap23** [comment]
@appapurapu 

Thanks man. I will test it . i will let u know.

**Comment by denglevi** [comment]
@appapurapu 
Hi appapurapu,i have test .aar file of you shared,but no success,i got the same error like "java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "random" referenced by "libMailCore.so"..."

**Comment by appapurapu** [comment]
Hi denglevi, its my fault as I compiled by disabling few things in build.sh file.
Now I gave full build and uploaded the binary and its size is around 34MB.
https://www.dropbox.com/s/g8xbv0hkxmgpb4r/ICS-RCSeClient07MAR13.rar?dl=0

Thanks,
RajaA

**Comment by denglevi** [comment]
@appapurapu 
Hi appapurapu,
is this link right? i got the file size is 6 MB,and there is not libMailCore.so or .aar file.

**Comment by appapurapu** [comment]
Hi,
Below link is correct only yaar. Might be some internet connection issue?
https://www.dropbox.com/s/rm8k9fmtyfw8t0y/mailcore2-android-1.aar?dl=0 

Thanks,
RajaA

**Comment by denglevi** [comment]
@appapurapu 
Hi appapurapu,
i have test lastest .aar file of you shared,i still got the same error like "java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "random" referenced by "libMailCore.so"..."

my build.gradle file like this as below
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.1"

    defaultConfig {
        applicationId "com.libmailcore.androidexample"
        minSdkVersion 19
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile(name: 'mailcore2-android-1', ext: 'aar')
    compile 'com.android.support:support-v4:21.0.2'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.android.support:appcompat-v7:21.0.2'
}

**Comment by appapurapu** [comment]
Hi,

I am able to run this on devices(emulator / target) with android lollipop version 21, but not on lower version.
it seems issue with android version 21 as it is not running on devices lower than 21.

I tried to change the max android version 21 to 20 in build.sh file but left with lot of compilation issues.
I require bit more time to understand this code as well as build environment to fix it.

Any one else can comment on it.

Thanks,
RajaA

**Comment by androidprodev** [comment]
@dinhviethoa 
Hi

I am unable to run the application on android device using the given .aar . I can successfully run it on emulator but when I run it on device I get the following error:

03-23 12:53:54.223  27409-27409/com.libmailcore.androidexample A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x766e6f6f in tid 27409 (.androidexample)
03-23 12:53:55.063  27449-27449/com.libmailcore.androidexample A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x766e6f6f in tid 27449 (.androidexample)

How can I fix this issue?

Also can you please help me compile the library by myself? Here is my question on stackoverflow:
http://stackoverflow.com/questions/29204197/how-to-build-mailcore2-library-for-android

**Comment by triton3** [comment]
>03-23 12:53:54.223 27409-27409/com.libmailcore.androidexample A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x766e6f6f in tid 27409 (.androidexample)

#1128 may help address your issue
