### ISSUE TITLE
implements new Gmail LIST extension instead of XLIST

### ISSUE THREAD

**Issue by dinhvh** [MailCore/mailcore2#12]

**Comment by deltadavid** [comment]
Hi :), I'm not too sure if this is a bug or a lack of understanding of Gmail LIST extension on my part. The INBOX folder does not seem to have the inbox flag.

existing flags for inbox folder: MCOIMAPFolderFlag.allZeros, MCOIMAPFolderFlag.None

is this because INBOX is always identifiable just by the path "INBOX" -> hence there is no need for a folderflag? (for what it's worth, when the folder is the inbox folder, the raw value of folder.flags.rawValue was 0)

https://gist.github.com/deltadavid/5be21b09f59b0f4b668c

**Comment by dinhviethoa** [comment]
Please stop commenting on this closed issue.
Please read:
https://tools.ietf.org/html/rfc6154
