### ISSUE TITLE
[MCOIMAPSession checkAccountOperation] stopped working for gmail accounts

### ISSUE THREAD

**Issue by MrRage** [MailCore/mailcore2#1259]
For what ever reason, I can't get checkAccountOperation to work with gmail accounts anymore. I have a checkout that was six months old and that failed, and I used a checkout that I did last night. What's strange is that this method works with my iCloud test account. Also noticed that the built in mail account is throwing an error as well but still able to check mail, so maybe the IMAP command backing this method is just broken on googles end. 

Mainly I'm filling this because is anyone else having this issue too?

**Comment by MrRage** [comment]
This is how the session looks just before requesting the checkAccountOperation. 

_imapSession = [[MCOIMAPSession alloc] init];
_imapSession.connectionType = 4 // MCOConnectionTypeTLS
_imapSession.port = 993
_imapSession.hostname = imap.gmail.com
_imapSession.password = correct
_imapSession.username = myEmail@myDoman

**Comment by dinhviethoa** [comment]
Could you let me know what result you get?

**Comment by MrRage** [comment]
Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

Sorry about that, forgot to include that. Let me update my MailCore2 and check again. This was with the older checkout.

**Comment by dinhviethoa** [comment]
could you show connectionLogger logs?
It sounds like you have restrictions on your account or 2-factor authentication is enabled.

**Comment by MrRage** [comment]
I have the log output in the form of printing the NSData objects, is there a better way of logging what is going on? I would just post the output here but not sure if there is sensitive information in it or not. 

I checked those two things this morning to make sure they were off. But I'll double check again.

[session setConnectionLogger:^(void * connectionID, MCOConnectionLogType type, NSData * data) {
        NSLog(@"event logged: %i withData: %@", type, data);
    }];

event logged: 0 withData: <>
event logged: 1 withData: <>
event logged: 0 withData: <>
event logged: 2 withData: <>
event logged: 0 withData: <>
(lldb)

**Comment by MrRage** [comment]
Okay verified that both two factor authentication is off and 'Allow less secure apps: ON'

**Comment by MrRage** [comment]
event logged: 0 withData: <2a204f4b 2047696d 61702072 65616479 20666f72 20726571 75657374 73206672 6f6d2032 342e3235 342e3830 2e313732 20636c37 6d623130 32323235 3134306f 65630d0a>
event logged: 1 withData: <31204341 50414249 4c495459 0d0a>
event logged: 0 withData: <2a204341 50414249 4c495459 20494d41 50347265 76312055 4e53454c 45435420 49444c45 204e414d 45535041 43452051 554f5441 20494420 584c4953 54204348 494c4452 454e2058 2d474d2d 4558542d 31205859 5a5a5920 5341534c 2d495220 41555448 3d584f41 55544832 20415554 483d504c 41494e20 41555448 3d504c41 494e2d43 4c49454e 54544f4b 454e2041 5554483d 584f4155 54482041 5554483d 4f415554 48424541 5245520d 0a31204f 4b205468 61747320 616c6c20 73686520 77726f74 65212063 6c376d62 31303232 32353134 306f6563 0d0a>
event logged: 2 withData: <32204c4f 47494e20 22647573 74696e40 35342e6f 72672220 55736572 77303070 7a770d0a>
event logged: 0 withData: <32204e4f 205b4155 5448454e 54494341 54494f4e 4641494c 45445d20 496e7661 6c696420 63726564 656e7469 616c7320 28466169 6c757265 290d0a>

**Comment by MrRage** [comment]
event logged: 0 withData: * OK Gimap ready for requests from 24.254.80.172 h6mb109203047oag
event logged: 1 withData: 1 CAPABILITY
event logged: 0 withData: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=XOAUTH AUTH=OAUTHBEARER
1 OK Thats all she wrote! h6mb109203047oag
event logged: 2 withData: 2 LOGIN "myEmail@12.org" SomepasswordThatWasRight
event logged: 0 withData: 2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)

**Comment by dinhviethoa** [comment]
I think that the logs speak themselves:
The credentials you provided are not correct.

**Comment by MrRage** [comment]
Well that was stupid of me. I'm not sure how I typed the wrong password in the iOS app and the right one when I tried testing it in gmail.

**Comment by guidedways** [comment]
I realize this is a closed thread however I'm seeing exactly the same - I am instead using OAuth and getting a valid token back, which I then use to check the account. I see 'AUTHENTICATIONFAILED' as well in the logs, in spite of the fact that the auth-token is granted correctly. I've tested with two different accounts, one with 2-factor auth and one without (although that shouldn't matter since I'm using OAuth2, so it should just work). Here's my code:

  MCOIMAPSession *imapSession = [[MCOIMAPSession alloc] init];
  imapSession.hostname = @"imap.gmail.com";
  imapSession.timeout = 12;
  imapSession.port = 993;
  imapSession.username = @"someuser@gmail.com";
  imapSession.password = nil;
  imapSession.connectionType = MCOConnectionTypeTLS;
  imapSession.OAuth2Token = [auth accessToken];
  imapSession.password = nil;
  imapSession.authType = MCOAuthTypeXOAuth2;

  MCOIMAPOperation *imapCheckOp = [imapSession checkAccountOperation];
  [imapCheckOp start:^(NSError *error) {
       if (error) { NSLog(@"Error: %@", error);}
  }];

This is what I see:

event logged:0x157a49be0 0 withData: * OK Gimap ready for requests from 85.255.234.23 21mb95420761wme


event logged:0x157a49be0 1 withData: 1 CAPABILITY


event logged:0x157a49be0 0 withData: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH

1 OK Thats all she wrote! 21mb95420762wme


event logged:0x157a49be0 2 withData: 2 AUTHENTICATE XOAUTH2 dXNlcj2ndWlkZWR3YXlzQGdtYWlsLmNvbQFhdXRoPUJlYXJlciB5YTI5Lkx3S0ZYNTJ0RmRDcFdDZTF3NVdXRThLOEpjdUVJS3lwRXhjR0xDc3o5cGh6OENuVTJsYlpTcTFacDVaQUk3NTFfTi1kAQE=


event logged:0x157a49be0 0 withData: + eyJzdGF0dXMiOiI0MEAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==


event logged:0x157a49be0 1 withData: 


event logged:0x157a49be0 0 withData: 2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)

**Comment by dinhviethoa** [comment]
Please check how OAuth2 is implemented on the sample app.

**Comment by guidedways** [comment]
I did, however it wasn't working for me. I ended up issuing an 'authorizeRequest'  on the newly returned GTMOAuth2Authentication object, which then worked. Not sure why, but perhaps the token returned was already expired or was going to expire immediately. It's now working for me.

**Comment by dinhviethoa** [comment]
You need to refresh the token when you're seeing authenticationfailed.
