### ISSUE TITLE
Provision to batch new messages using syncMessagesWithFolder:

### ISSUE THREAD

**Issue by shrishaster** [MailCore/mailcore2#1364]
I want to batch the number of new messages I get from the operation:

`MCOIMAPFetchMessagesOperation * op = [session syncMessagesWithFolder:@"INBOX"
                                                              requestKind:MCOIMAPMessagesRequestKindUID
                                                                     uids:MCORangeMake(1, UINT64_MAX)
                                                                   modSeq:lastModSeq];
     [op start:^(NSError * error, NSArray * messages, MCOIndexSet * vanishedMessages) {
       NSLog(@"added or modified messages: %@", messages);
       NSLog(@"deleted messages: %@", vanishedMessages);
     }];`

Currently it takes a range of `1` to `UINT64_MAX`. This becomes a problem when the user syncs his mail after a long time when he might have 1000-2000 new mails coming in all of a sudden. Changing the range of uids does not work because you dont know what range message uids changed. They can be old mails in the All Mail folder.

So any suggestion to batch them say 100 in each call?

**Comment by dinhviethoa** [comment]
I haven't experimented enough on using `-syncMessages`. But here's my take on it:
- With `folderInfo`, you can grab the most recent UID (nextUID): -> b
- You have the latest UID you fetched in hands -> a
- You have your interval a:b. That's the new emails to fetch, with fetch or sync. You can split that interval in chunks of 100.
- `-syncMessages` is rather interesting to get flags that changed recently on emails that you already fetched before. I think you have the list of those emails locally. You could split that in chunks of 1000 / 10000. Then `-syncMessages` on each of those chunks. You might want to choose a high number for those chunks since it's usually rare that changes happens on old emails.

**Comment by shrishaster** [comment]
OK.
I had thought about the points you mentioned but it won't be very efficient right?

Any way to modify mailcore2 source to add batching on the IMAP commands itself?

**Comment by dinhviethoa** [comment]
I'm not sure what's the efficiency you're talking about.
I don't think I'll modify mailcore2 for now.

**Comment by lukelan** [comment]
@shrishaster: It is great if you can share the code that you did "Any way to modify mailcore2 source to add batching on the IMAP commands itself?". 
@dinhviethoa: thank for your advise, I currently follow that way.
