### ISSUE TITLE
[bug] - failed downloading https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip

### ISSUE THREAD

**Issue by rbosch** [MailCore/mailcore2#1948]
> failed downloading 'https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip'  which is required by binary target 'MailCore2': downloadError("Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x7fd087cdc900 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en1, ipv4, dns, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <978D3610-8C5E-493F-AE29-2BE0D42FA183>.<4>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDownloadTask <978D3610-8C5E-493F-AE29-2BE0D42FA183>.<4>\"\n), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, NSErrorFailingURLKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, _kCFStreamErrorDomainKey=12}")

**Platform(s)**
MacOS 12.3 / XCode 13.4.1

Trying to add the `mailcore2` as package,  branch -> master

https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip 

downloads.maddux.cloud doesn't exist anymore.

**Comment by IMCHO** [comment]
@dinhvh

**Comment by DavidMolnar-RS** [comment]
@dinhvh the framework download link for MacOS is broken.  Thanks in advance.

**Comment by pendowski** [comment]
Does anyone have a cache of this file to put somewhere else? @mattmaddux maybe?

**Comment by mattmaddux** [comment]
Ah! Thanks for the heads up. I can restore that later on today. The removal was accidental. However, when I first made the PR that included the Package.swift I had asked that it could be hosted long term at the same location as the Cocoapod download (https://d.etpan.org/) rather than the temporary location used for the initial PR. And honestly thought that change had been done quite a bit ago. Do we know who handles that domain?

**Comment by pendowski** [comment]
Yea, it should be hosted somewhere outside of your personal hosting for sure. As for the etpan.org, my guess would be @dinhvh
I think the zip file is smaller than 50MB so it could be hosted on GitHub as well as an alternative?

**Comment by dinhvh** [comment]
@mattmaddux how do you produce this file?

**Comment by mattmaddux** [comment]
@dinhvh In PR #1887 I include some instructions. Basically:

1. Run the script build-mailcore2-xcframework-spm.sh, which spits out an xcframework.zip file and a checksum
2. Upload the resulting file to your host
3. Update Package.swift with the new url and checksum
4. Commit, and you're good to go

It's been a long time since I built with that script, so I can't say for sure it still works.

I checked, and the builds are only about 14 MB, so I'm attaching both of the ones that I have here. Like @pendowski said, since they're small-ish, we could just include them in the repo and update the Package.swift with the GitHub path.

In fact I could make that change and create a PR if that would be helpful.

[MailCore2-2020-09-24.xcframework.zip](https://github.com/MailCore/mailcore2/files/9247563/MailCore2-2020-09-24.xcframework.zip) - (Checksum c3479968c758094165fb0b4de5ca7dd9f8aafac423388c51406c447f69a1b853)

[MailCore2-2020-09-17.xcframework.zip](https://github.com/MailCore/mailcore2/files/9247564/MailCore2-2020-09-17.xcframework.zip)

**Comment by mattmaddux** [comment]
Okay, I've gone ahead and created PR #1949. It adds the two binaries I build before to the repo and updates the Package.swift so SPM should work correctly. Updating the binaries might still be an issue. I will see when I have time to check on that.

**Comment by haithngn** [comment]
Closed - https://github.com/MailCore/mailcore2/pull/1949

**Comment by IMCHO** [comment]
~~Same error occurs in intel Mac when I installed by SPM.~~
~~@mattmaddux @dinhvh Any suggestion?~~
Never mind. It works now.
