### ISSUE TITLE
MessagedID is not right

### ISSUE THREAD

**Issue by zhangjiangshan** [MailCore/mailcore2#719]
The messageID will be created by Mailcore2 when I received mail from server which has no messageID.But I want to do some process with none messageID mail.How can I solve this problem without changed Mailcore2 code?

**Comment by guidedways** [comment]
I realize this is a closed issue but commenting on the last message. Doesn't the 'messageIDAutoGenerated' flag serve the purpose? I'm guessing if this is YES it would mean mailcore assigned an ID automatically, and so we could resort to some other way of identifying the message.

**Comment by lksnmnn** [comment]
Well, if MailCore does set this flag, it would actually help a lot. I think we haven't experienced any problems with this issue any longer, but I don't know exactly why (right now).

I will dive into our code and check it out :)

**Comment by ikemuc** [comment]
OK, found the MCOMessageHeader.isMessageIDAutoGenerated now and can use this to prevent getting a different header all the time.
IMHO it would be better to get an auto-generated header, which is always the same for one particular message in IMAP, e.g. based on headers, which don't change (From, To, CC, BCC, Date etc.)

**Comment by lksnmnn** [comment]
Yes, you have to use this flag to detect messages without server-side messageIDs. The fields From, To, CC, BCC, Date etc. are not unique and cannot be used to identify a message correctly (the message could be in your inbox and in another folder, the headers would be the same).

To work around this you could use folder+uid to identify the specific message. And yes, I would prefer MailCore to generate the messageID by using those identifiers in order to yield the same messageID for the same message every-time we check the folder.

Maybe we could try to fix this and make a PR?
